language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.02
    TESTS=false
    EXTRA_REMOTES="https://github.com/ocamllabs/opam-repo-dev.git"
    PINS="unix-unistd:https://github.com/dsheets/ocaml-unix-unistd.git#0.3.0-gamma"
